import { useState, useEffect } from "react";

const CREATOR_FEE=0.015,JOINER_FEE=0.025,SYM="USDC",MN="var(--mono)";
const CATS=[{id:"all",l:"All"},{id:"1-50",l:"$1–$50"},{id:"50-250",l:"$50–$250"},{id:"250-1k",l:"$250–$1K"},{id:"1k+",l:"$1K+"}];
const ACOL=[["#6366f1","#8b5cf6"],["#ec4899","#f43f5e"],["#f59e0b","#f97316"],["#22c55e","#10b981"],["#3b82f6","#2563eb"],["#14b8a6","#0d9488"],["#a855f7","#7c3aed"],["#ef4444","#dc2626"],["#06b6d4","#0891b2"],["#84cc16","#65a30d"]];
const I={
  search:(s=16)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>,
  plus:(s=14)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>,
  x:(s=18)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>,
  trophy:(s=18)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6"/><path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18"/><path d="M4 22h16"/><path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20 7 22"/><path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20 17 22"/><path d="M18 2H6v7a6 6 0 0 0 12 0V2Z"/></svg>,
  wallet:(s=16)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 5v14a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a1 1 0 0 0 0 2h4v-2Z"/></svg>,
  history:(s=18)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/><path d="M12 7v5l4 2"/></svg>,
  check:(s=14,c="#22c55e")=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke={c} strokeWidth="3" strokeLinecap="round"><polyline points="20 6 9 17 4 12"/></svg>,
  xc:(s=14)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg>,
  crown:(s=16,c="#eab308")=><svg width={s} height={s} viewBox="0 0 24 24" fill={c} stroke={c} strokeWidth="1.5"><path d="M2 4l3 12h14l3-12-6 7-4-9-4 9-6-7z"/><path d="M3 20h18"/></svg>,
  users:(s=14)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>,
  info:(s=13)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>,
  gift:(s=18)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 12 20 22 4 22 4 12"/><rect x="2" y="7" width="20" height="5"/><line x1="12" y1="22" x2="12" y2="7"/><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"/><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"/></svg>,
  help:(s=18)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>,
  file:(s=16)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>,
  shield:(s=16)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
  copy:(s=14)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>,
  chev:(s=14)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="6 9 12 15 18 9"/></svg>,
  menu:(s=20)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="4" y1="12" x2="20" y2="12"/><line x1="4" y1="6" x2="20" y2="6"/><line x1="4" y1="18" x2="20" y2="18"/></svg>,
  home:(s=20)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>,
  coin:(s=18)=><svg width={s} height={s} viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" fill="#2775CA" stroke="#1a5fb4" strokeWidth="1.5"/><text x="12" y="16.5" textAnchor="middle" fill="#fff" fontSize="12" fontWeight="800">$</text></svg>,
};
const HS=({size=36,muted=false})=><svg width={size} height={size} viewBox="0 0 48 48" fill="none"><circle cx="24" cy="24" r="22" fill={muted?"rgba(34,197,94,.03)":"rgba(34,197,94,.1)"} stroke={muted?"rgba(34,197,94,.12)":"#22c55e"} strokeWidth="2"/><text x="24" y="30" textAnchor="middle" fill={muted?"rgba(34,197,94,.25)":"#22c55e"} fontSize="17" fontWeight="800">H</text></svg>;
const TS=({size=36,muted=false})=><svg width={size} height={size} viewBox="0 0 48 48" fill="none"><circle cx="24" cy="24" r="22" fill={muted?"rgba(239,68,68,.03)":"rgba(239,68,68,.1)"} stroke={muted?"rgba(239,68,68,.12)":"#ef4444"} strokeWidth="2"/><text x="24" y="30" textAnchor="middle" fill={muted?"rgba(239,68,68,.25)":"#ef4444"} fontSize="17" fontWeight="800">T</text></svg>;
const Dot=()=><span style={{width:6,height:6,background:"#22c55e",borderRadius:"50%",display:"inline-block",animation:"pulse 1.5s ease infinite",flexShrink:0}}/>;
const Av=({u,size=30})=>{const c=ACOL[u.ci%ACOL.length];return<div style={{width:size,height:size,borderRadius:size>26?9:6,background:`linear-gradient(135deg,${c[0]},${c[1]})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:size*.3,fontWeight:700,color:"#fff",flexShrink:0}}>{u.in}</div>};

const NMS=["CryptoKing","FlipMaster","LuckyDoge","MoonShot","DiamondH","NightOwl","ShadowBet","GoldenFlip","IronWolf","SilverFox","DarkHorse","WildCard","HighRoller","ThunderB","PhantomAce","NeonViper","StormChase","BlazeRun","FrostByte","ZenTrader"];
const gu=()=>{const n=NMS[Math.floor(Math.random()*NMS.length)];return{name:`${n}${Math.floor(Math.random()*999)}`,in:n.slice(0,2).toUpperCase(),ci:Math.floor(Math.random()*ACOL.length)}};
const gm=()=>{const m=[];for(let i=0;i<24;i++){const d=Math.random()>.42,b=[5,10,25,50,100,250,500,1000][Math.floor(Math.random()*8)],cr=gu(),op=d?gu():null,cc=Math.random()>.5?"heads":"tails",r=d?(Math.random()>.5?"heads":"tails"):null;m.push({id:`m${i}`,cr,op,ba:b,st:d?"completed":"live",res:r,cc,ta:`${Math.floor(Math.random()*59)+1}m ago`,cat:Date.now()-Math.floor(Math.random()*36e5)})}return m};
const glb=()=>{const l=[];for(let i=0;i<15;i++){const u=gu(),t=Math.floor(Math.random()*800)+50,w=Math.floor(Math.random()*30)+50;l.push({rk:i+1,...u,wr:w,tw:Math.floor(t*(w/100)),pf:Math.floor(Math.random()*5e4)-5e3})}return l.sort((a,b)=>b.pf-a.pf).map((x,i)=>({...x,rk:i+1}))};
const ghi=()=>{const h=[];for(let i=0;i<14;i++){const w=Math.random()>.42,a=[5,10,25,50,100,250,500][Math.floor(Math.random()*7)],op=gu(),mc=Math.random()>.5?"heads":"tails",r=w?mc:(mc==="heads"?"tails":"heads"),ic=Math.random()>.5,f=a*(ic?CREATOR_FEE:JOINER_FEE);h.push({id:`h${i}`,op,a,w,res:r,mc,ic,fee:f,net:w?(a-f):-(a+f),t:`${Math.floor(Math.random()*23)+1}h ago`})}return h};

const CSS=`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600;700&display=swap');
*{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#080b11;--card:#0f1319;--surface:#181e28;--border:#1c2333;--border2:#2a3347;--t:#e8ecf2;--t2:#8a919c;--t3:#4a5264;--g:#22c55e;--gd:rgba(34,197,94,.08);--gb:rgba(34,197,94,.18);--r:#ef4444;--rd:rgba(239,68,68,.08);--rb:rgba(239,68,68,.18);--y:#eab308;--u:#2775CA;--f:'DM Sans',-apple-system,sans-serif;--mono:'JetBrains Mono',monospace}
body{background:var(--bg);color:var(--t);font-family:var(--f);-webkit-font-smoothing:antialiased}
::-webkit-scrollbar{width:4px}::-webkit-scrollbar-thumb{background:var(--border2);border-radius:3px}
@keyframes fu{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
@keyframes fi{from{opacity:0}to{opacity:1}}
@keyframes pulse{0%,100%{opacity:1}50%{opacity:.3}}
@keyframes si{from{opacity:0;transform:scale(.97)}to{opacity:1;transform:none}}
@keyframes gs{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}
@keyframes sp{0%,100%{opacity:1}50%{opacity:.45}}
.mc{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:14px;cursor:pointer;transition:all .18s;position:relative;overflow:hidden}
.mc:hover{border-color:var(--border2);transform:translateY(-1px);box-shadow:0 6px 24px rgba(0,0,0,.2)}
.mc.live{border-color:rgba(34,197,94,.15)}.mc.live::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,#22c55e,#16a34a,#22c55e);background-size:200% 100%;animation:gs 2s ease infinite}
.bg{background:linear-gradient(135deg,#22c55e,#16a34a);color:#fff;border:none;padding:10px 18px;border-radius:8px;font-weight:600;font-size:13px;cursor:pointer;transition:all .18s;display:inline-flex;align-items:center;gap:6px;font-family:var(--f)}
.bg:hover{box-shadow:0 4px 14px rgba(34,197,94,.22);transform:translateY(-1px)}.bg:disabled{opacity:.35;cursor:not-allowed;transform:none;box-shadow:none}
.bh{background:var(--gd);color:var(--g);border:1px solid var(--gb);padding:10px 18px;border-radius:8px;font-weight:600;font-size:13px;cursor:pointer;transition:all .12s;flex:1;text-align:center;font-family:var(--f)}
.bh:hover{background:rgba(34,197,94,.12)}
.bt{background:var(--rd);color:var(--r);border:1px solid var(--rb);padding:10px 18px;border-radius:8px;font-weight:600;font-size:13px;cursor:pointer;transition:all .12s;flex:1;text-align:center;font-family:var(--f)}
.bt:hover{background:rgba(239,68,68,.12)}
.mbg{position:fixed;inset:0;background:rgba(0,0,0,.7);backdrop-filter:blur(10px);z-index:200;display:flex;align-items:center;justify-content:center;animation:fi .12s ease}
.mdc{background:var(--card);border:1px solid var(--border2);border-radius:16px;padding:20px;width:100%;max-width:480px;max-height:90vh;overflow-y:auto;animation:si .2s ease;margin:16px}
.inp{width:100%;background:var(--bg);border:1px solid var(--border);border-radius:8px;padding:11px 14px;color:var(--t);font-size:14px;outline:none;transition:border .15s;font-family:var(--f)}
.inp:focus{border-color:var(--g);box-shadow:0 0 0 3px rgba(34,197,94,.06)}
.ch{padding:5px 13px;border-radius:20px;cursor:pointer;transition:all .12s;font-size:11px;font-weight:600;color:var(--t3);border:1px solid transparent;background:none;white-space:nowrap;font-family:var(--f)}
.ch:hover{color:var(--t)}.ch.a{color:var(--t);background:var(--gd);border-color:var(--gb)}
.bd{padding:2px 7px;border-radius:5px;font-size:10px;font-weight:700}
.bn{position:fixed;bottom:0;left:0;right:0;background:rgba(8,11,17,.96);backdrop-filter:blur(20px);border-top:1px solid var(--border);z-index:100;display:none;padding:4px 0 8px}
.bi{flex:1;display:flex;flex-direction:column;align-items:center;gap:2px;padding:6px 0;cursor:pointer;color:var(--t3);transition:color .12s;border:none;background:none;font-family:var(--f)}
.bi.a{color:var(--g)}.bi span{font-size:9px;font-weight:600}
.fn{display:flex;align-items:center;gap:5px;padding:7px 10px;background:rgba(39,117,202,.06);border:1px solid rgba(39,117,202,.1);border-radius:7px;font-size:11px;color:#93c5fd}
@media(max-width:768px){.bn{display:flex}.mw{padding-bottom:72px !important}.dn{display:none !important}.g4{grid-template-columns:repeat(2,1fr) !important}.mg{grid-template-columns:1fr !important}.pg{grid-template-columns:1fr !important}.lr{grid-template-columns:36px 1fr 60px 72px !important}.lr .hm{display:none !important}.hi{padding:0 12px !important}.ms{display:block !important}}
@media(max-width:480px){.g4{grid-template-columns:1fr !important}}`;

function AC({flipping,result}){const[r,setR]=useState(0);useEffect(()=>{if(!flipping)return;let f,v=0;const a=()=>{v+=18;setR(v);if(v<1800)f=requestAnimationFrame(a);else setR(result==="heads"?0:180)};f=requestAnimationFrame(a);return()=>cancelAnimationFrame(f)},[flipping,result]);const h=Math.floor(r/180)%2===0;return<div style={{width:90,height:90,perspective:600,margin:"0 auto"}}><div style={{width:"100%",height:"100%",borderRadius:"50%",transform:`rotateX(${r}deg)`,transition:flipping?"none":"transform .3s",background:h?"linear-gradient(135deg,#22c55e,#16a34a)":"linear-gradient(135deg,#ef4444,#dc2626)",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:`0 0 24px ${h?"rgba(34,197,94,.25)":"rgba(239,68,68,.25)"},inset 0 -2px 8px rgba(0,0,0,.3)`,border:"2px solid rgba(255,255,255,.1)"}}><span style={{fontSize:36,fontWeight:900,color:"#fff",textShadow:"0 2px 4px rgba(0,0,0,.4)"}}>{h?"H":"T"}</span></div></div>}

function CreateMod({close,bal}){const[amt,setAmt]=useState("");const[ch,setCh]=useState("heads");const n=parseInt(amt)||0,fee=n*CREATOR_FEE,total=n+fee,ok=n>=1&&n===Math.floor(n)&&total<=bal;
return<div className="mbg" onClick={close}><div className="mdc" onClick={e=>e.stopPropagation()}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div><div style={{fontSize:17,fontWeight:800}}>Create Match</div><div style={{color:"var(--t3)",fontSize:11,marginTop:1}}>Set stake and pick a side</div></div><button onClick={close} style={{background:"rgba(255,255,255,.03)",border:"none",color:"var(--t3)",cursor:"pointer",padding:7,borderRadius:8}}>{I.x()}</button></div>
<div style={{marginBottom:18}}><label style={{fontSize:9,fontWeight:700,color:"var(--t3)",display:"block",marginBottom:5,textTransform:"uppercase",letterSpacing:1}}>Amount ({SYM})</label><div style={{position:"relative"}}><span style={{position:"absolute",left:13,top:"50%",transform:"translateY(-50%)",fontSize:18,fontWeight:800,color:"var(--u)"}}>$</span><input className="inp" type="text" inputMode="numeric" placeholder="0" value={amt} onChange={e=>setAmt(e.target.value.replace(/[^0-9]/g,""))} style={{paddingLeft:32,fontSize:20,fontWeight:800,fontFamily:MN,height:50}}/></div>
<div style={{display:"flex",gap:4,marginTop:6,flexWrap:"wrap"}}>{[5,10,25,50,100,250,500,1000].map(p=><button key={p} onClick={()=>setAmt(String(p))} style={{padding:"4px 10px",borderRadius:7,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:MN,background:n===p?"var(--gd)":"rgba(255,255,255,.02)",border:`1px solid ${n===p?"var(--gb)":"var(--border)"}`,color:n===p?"var(--g)":"var(--t3)"}}>${p}</button>)}</div></div>
<div style={{marginBottom:18}}><label style={{fontSize:9,fontWeight:700,color:"var(--t3)",display:"block",marginBottom:6,textTransform:"uppercase",letterSpacing:1}}>Your Pick</label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{["heads","tails"].map(s=>{const sel=ch===s,isH=s==="heads";return<button key={s} onClick={()=>setCh(s)} style={{padding:14,borderRadius:11,cursor:"pointer",textAlign:"center",background:sel?(isH?"var(--gd)":"var(--rd)"):"var(--bg)",border:`2px solid ${sel?(isH?"var(--g)":"var(--r)"):"var(--border)"}`,transition:"all .12s"}}>{isH?<HS size={32}/>:<TS size={32}/>}<div style={{fontWeight:700,fontSize:12,marginTop:5,color:sel?(isH?"var(--g)":"var(--r)"):"var(--t3)"}}>{isH?"Heads":"Tails"}</div></button>})}</div></div>
<div className="fn" style={{marginBottom:10}}>{I.info()} Creator fee: 1.5% on top of bet</div>
{n>=1&&<div style={{padding:12,background:"rgba(34,197,94,.02)",borderRadius:9,border:"1px solid rgba(34,197,94,.06)",marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:5,fontSize:12}}><span style={{color:"var(--t2)"}}>Bet</span><span style={{fontFamily:MN}}>${n}</span></div><div style={{display:"flex",justifyContent:"space-between",marginBottom:5,fontSize:12}}><span style={{color:"var(--t2)"}}>Fee (1.5%)</span><span style={{fontFamily:MN,color:"var(--t3)"}}>${fee.toFixed(2)}</span></div><div style={{borderTop:"1px solid rgba(255,255,255,.03)",paddingTop:5,display:"flex",justifyContent:"space-between",fontSize:13}}><span style={{fontWeight:600}}>Total</span><span style={{fontWeight:800,fontFamily:MN}}>${total.toFixed(2)} {SYM}</span></div></div>}
<button className="bg" disabled={!ok} style={{width:"100%",justifyContent:"center",padding:12,fontSize:13,borderRadius:11}}>{I.plus(13)} Create{n>0?` · $${total.toFixed(2)}`:""}</button>
</div></div>}

function DetailMod({m,close,bal}){const[side,setSide]=useState(null);const[step,setStep]=useState(0);const[result,setResult]=useState(null);const fee=m.ba*JOINER_FEE,total=m.ba+fee,cJ=total<=bal&&side&&m.st==="live"&&step===0;
const doF=()=>{if(!cJ)return;setStep(1);setTimeout(()=>setStep(2),700);setTimeout(()=>{const r=Math.random()>.5?"heads":"tails";setResult(r);setStep(3)},3000)};
return<div className="mbg" onClick={close}><div className="mdc" onClick={e=>e.stopPropagation()} style={{maxWidth:440}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}>
{step===0&&m.st==="live"&&<div style={{display:"flex",alignItems:"center",gap:4,fontSize:11,fontWeight:700,color:"var(--g)"}}><Dot/> Open Match</div>}
{step>0&&step<3&&<div style={{fontSize:11,fontWeight:700,color:"var(--y)",animation:"sp 1s ease infinite"}}>{step===1?"Submitting...":"Flipping..."}</div>}
{(step===3||m.st==="completed")&&<span style={{fontSize:11,color:"var(--t2)"}}>Complete</span>}
<button onClick={close} style={{background:"rgba(255,255,255,.03)",border:"none",color:"var(--t3)",cursor:"pointer",padding:5,borderRadius:7}}>{I.x(16)}</button></div>
{step>0&&<div style={{display:"flex",justifyContent:"center",gap:3,marginBottom:14}}>{["Join","Flip","Result"].map((s,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:3}}><div style={{width:20,height:20,borderRadius:"50%",fontSize:9,fontWeight:700,display:"flex",alignItems:"center",justifyContent:"center",background:step>i?"var(--g)":"var(--border)",color:step>i?"#fff":"var(--t3)",transition:"all .3s"}}>{step>i?I.check(9,"#fff"):i+1}</div><span style={{fontSize:9,fontWeight:600,color:step>i?"var(--g)":"var(--t3)"}}>{s}</span>{i<2&&<div style={{width:16,height:1,background:step>i+1?"var(--g)":"var(--border)"}}/>}</div>)}</div>}
<div style={{marginBottom:16,textAlign:"center"}}><AC flipping={step===2} result={result||m.res||"heads"}/>{step===3&&result&&<div style={{marginTop:10,animation:"fu .3s ease"}}><div style={{fontSize:16,fontWeight:800,color:result==="heads"?"var(--g)":"var(--r)"}}>{result==="heads"?"Heads!":"Tails!"}</div><div style={{color:"var(--t2)",fontSize:12,marginTop:1}}>{result===side?"You won!":"You lost!"}</div></div>}</div>
<div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:14,marginBottom:14,padding:14,background:"var(--bg)",borderRadius:11,border:"1px solid var(--border)"}}>
<div style={{textAlign:"center",flex:1}}><div style={{display:"flex",justifyContent:"center"}}><Av u={m.cr} size={32}/></div><div style={{fontWeight:600,fontSize:11,marginTop:5}}>{m.cr.name.slice(0,12)}</div><div style={{fontSize:9,color:m.cc==="heads"?"var(--g)":"var(--r)",fontWeight:600}}>{m.cc==="heads"?"Heads":"Tails"}</div></div>
<div style={{fontSize:9,fontWeight:800,color:"var(--t3)",background:"var(--border)",padding:"3px 8px",borderRadius:5}}>VS</div>
<div style={{textAlign:"center",flex:1}}>{m.op?<><div style={{display:"flex",justifyContent:"center"}}><Av u={m.op} size={32}/></div><div style={{fontWeight:600,fontSize:11,marginTop:5}}>{m.op.name.slice(0,12)}</div></>:<><div style={{width:32,height:32,borderRadius:8,background:"var(--border)",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto",border:"2px dashed var(--border2)"}}>{I.users(12)}</div><div style={{fontSize:10,color:"var(--t3)",marginTop:5}}>Waiting...</div></>}</div></div>
<div style={{textAlign:"center",marginBottom:16}}><div style={{fontSize:24,fontWeight:800,fontFamily:MN,color:"var(--g)"}}>${(m.ba*(m.op?2:1)).toLocaleString()}<span style={{fontSize:10,color:"var(--t3)",fontWeight:500,marginLeft:3}}>{SYM}</span></div><div style={{fontSize:10,color:"var(--t3)"}}>50/50 odds</div></div>
{m.st==="live"&&step===0&&<><label style={{fontSize:9,fontWeight:700,color:"var(--t3)",display:"block",marginBottom:6,textTransform:"uppercase",letterSpacing:1}}>Pick Your Side</label>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginBottom:12}}>{["heads","tails"].map(s=>{const tk=s===m.cc,sel=side===s,isH=s==="heads";return<button key={s} onClick={()=>!tk&&setSide(s)} style={{padding:12,borderRadius:9,cursor:tk?"not-allowed":"pointer",textAlign:"center",background:sel?(isH?"var(--gd)":"var(--rd)"):"transparent",border:`2px solid ${tk?"var(--border)":sel?(isH?"var(--g)":"var(--r)"):"var(--border)"}`,opacity:tk?.25:1,transition:"all .12s"}}>{isH?<HS size={28} muted={tk}/>:<TS size={28} muted={tk}/>}<div style={{fontWeight:700,fontSize:11,marginTop:3,color:tk?"var(--t3)":sel?(isH?"var(--g)":"var(--r)"):"var(--t2)"}}>{isH?"Heads":"Tails"}</div>{tk&&<div style={{fontSize:8,color:"var(--t3)"}}>Taken</div>}</button>})}</div>
<div className="fn" style={{marginBottom:8}}>{I.info()} Joiner fee: 2.5% + entropy fee</div>
<div style={{padding:10,background:"rgba(255,255,255,.01)",borderRadius:8,border:"1px solid var(--border)",marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:3,fontSize:11}}><span style={{color:"var(--t2)"}}>Bet</span><span style={{fontFamily:MN}}>${m.ba.toLocaleString()}</span></div><div style={{display:"flex",justifyContent:"space-between",marginBottom:3,fontSize:11}}><span style={{color:"var(--t2)"}}>Fee (2.5%)</span><span style={{fontFamily:MN,color:"var(--t3)"}}>${fee.toFixed(2)}</span></div><div style={{borderTop:"1px solid rgba(255,255,255,.02)",paddingTop:3,display:"flex",justifyContent:"space-between",fontSize:12}}><span style={{fontWeight:600}}>Total</span><span style={{fontWeight:800,fontFamily:MN}}>${total.toFixed(2)}</span></div></div>
<button className="bg" disabled={!cJ} onClick={doF} style={{width:"100%",justifyContent:"center",padding:12,fontSize:13,borderRadius:11}}>{I.coin(15)} Join & Flip · ${total.toFixed(2)}</button></>}
</div></div>}

export default function App(){
const[pg,setPg]=useState("matches");const[cat,setCat]=useState("all");const[sq,setSq]=useState("");
const[matches]=useState(gm);const[lb]=useState(glb);const[hist]=useState(ghi);
const[showC,setShowC]=useState(false);const[showD,setShowD]=useState(null);
const[sort,setSort]=useState("newest");const[sf,setSf]=useState("all");
const[bal]=useState(4827);const[dd,setDd]=useState(false);
const nav=p=>{setPg(p);setDd(false)};const mP=["matches","leaderboard","bets","referral"];const mp=["faq","terms","privacy","about"];

const filt=matches.filter(m=>{if(sf!=="all"&&m.st!==sf)return false;if(cat!=="all"){const a=m.ba,rg={"1-50":[1,50],"50-250":[50,250],"250-1k":[250,1000],"1k+":[1000,Infinity]};const[mn,mx]=rg[cat]||[0,Infinity];if(a<mn||a>mx)return false}if(sq){const q=sq.toLowerCase();return m.cr.name.toLowerCase().includes(q)||(m.op?.name.toLowerCase().includes(q))}return true}).sort((a,b)=>sort==="newest"?b.cat-a.cat:sort==="highest"?b.ba-a.ba:a.ba-b.ba);

return<div style={{minHeight:"100vh"}}><style>{CSS}</style>
{/* HEADER */}
<header style={{borderBottom:"1px solid var(--border)",background:"rgba(8,11,17,.94)",backdropFilter:"blur(16px)",position:"sticky",top:0,zIndex:100}}>
<div className="hi" style={{maxWidth:1200,margin:"0 auto",padding:"0 20px",display:"flex",alignItems:"center",height:52,gap:12}}>
<div style={{display:"flex",alignItems:"center",gap:7,cursor:"pointer",flexShrink:0}} onClick={()=>nav("matches")}><div style={{width:28,height:28,borderRadius:7,display:"flex",alignItems:"center",justifyContent:"center",background:"linear-gradient(135deg,#22c55e,#16a34a)"}}>{I.coin(15)}</div><span style={{fontSize:15,fontWeight:800,letterSpacing:"-.3px"}}>Random<span style={{color:"var(--g)"}}>Markets</span></span></div>
<nav className="dn" style={{display:"flex",gap:1,marginLeft:16}}>{[{id:"matches",l:"Markets"},{id:"leaderboard",l:"Leaderboard"},{id:"bets",l:"My Bets"},{id:"referral",l:"Referrals"}].map(x=><button key={x.id} onClick={()=>nav(x.id)} style={{padding:"5px 10px",borderRadius:7,border:"none",background:pg===x.id?"rgba(255,255,255,.05)":"none",color:pg===x.id?"var(--t)":"var(--t2)",fontSize:12,fontWeight:500,cursor:"pointer",fontFamily:"var(--f)",transition:"all .12s"}}>{x.l}</button>)}
<div style={{position:"relative"}}><button onClick={()=>setDd(!dd)} style={{padding:"5px 8px",borderRadius:7,border:"none",background:mp.includes(pg)?"rgba(255,255,255,.05)":"none",color:"var(--t2)",fontSize:12,fontWeight:500,cursor:"pointer",fontFamily:"var(--f)",display:"flex",alignItems:"center",gap:3}}>More {I.chev(11)}</button>{dd&&<div style={{position:"absolute",top:36,right:0,background:"var(--card)",border:"1px solid var(--border2)",borderRadius:10,padding:4,minWidth:160,zIndex:50,boxShadow:"0 10px 32px rgba(0,0,0,.4)"}}>{[{id:"faq",l:"How It Works",i:I.help(14)},{id:"about",l:"About",i:I.info(14)},{id:"terms",l:"Terms",i:I.file(14)},{id:"privacy",l:"Privacy",i:I.shield(14)}].map(x=><button key={x.id} onClick={()=>nav(x.id)} style={{width:"100%",textAlign:"left",padding:"8px 10px",border:"none",background:pg===x.id?"rgba(255,255,255,.03)":"none",color:"var(--t)",fontSize:12,cursor:"pointer",borderRadius:6,display:"flex",alignItems:"center",gap:7,fontFamily:"var(--f)"}}>{x.i} {x.l}</button>)}</div>}</div></nav>
<div style={{flex:1}}/>
<div style={{display:"flex",alignItems:"center",gap:8}}><div style={{display:"flex",alignItems:"center",gap:5,background:"var(--card)",border:"1px solid var(--border)",borderRadius:9,padding:"5px 10px"}}>{I.coin(14)}<span style={{fontWeight:700,fontFamily:MN,fontSize:12}}>{bal.toLocaleString()}</span></div><button style={{background:"linear-gradient(135deg,var(--u),#1a5fb4)",border:"none",color:"#fff",padding:"6px 12px",borderRadius:9,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"var(--f)",display:"flex",alignItems:"center",gap:4}}>{I.wallet(13)} <span className="dn">Connect</span></button></div>
</div></header>

{/* BOTTOM NAV */}
<nav className="bn">{[{id:"matches",l:"Markets",i:I.home},{id:"leaderboard",l:"Ranks",i:I.trophy},{id:"bets",l:"My Bets",i:I.history},{id:"referral",l:"Refer",i:I.gift},{id:"faq",l:"More",i:I.menu}].map(x=><button key={x.id} className={`bi ${pg===x.id||(x.id==="faq"&&mp.includes(pg))?"a":""}`} onClick={()=>nav(x.id)}>{x.i(19)}<span>{x.l}</span></button>)}</nav>

<main className="mw" style={{maxWidth:1200,margin:"0 auto",padding:"16px 16px 20px"}} onClick={()=>dd&&setDd(false)}>

{/* MATCHES - NO STATS BAR */}
{pg==="matches"&&<div style={{animation:"fu .3s ease"}}>
<div style={{marginBottom:12,display:"none"}} className="ms"><div style={{position:"relative"}}><div style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",color:"var(--t3)"}}>{I.search(14)}</div><input className="inp" placeholder="Search..." value={sq} onChange={e=>setSq(e.target.value)} style={{paddingLeft:32,height:38,fontSize:13}}/></div></div>
<div style={{display:"flex",alignItems:"center",gap:8,marginBottom:14,flexWrap:"wrap"}}><div style={{display:"flex",gap:3,overflow:"auto",flex:1,paddingBottom:1}}>{CATS.map(c=><button key={c.id} className={`ch ${cat===c.id?"a":""}`} onClick={()=>setCat(c.id)}>{c.l}</button>)}</div>
<div style={{display:"flex",gap:1,background:"var(--card)",borderRadius:7,padding:2,border:"1px solid var(--border)"}}>{["all","live","completed"].map(s=><button key={s} onClick={()=>setSf(s)} style={{padding:"3px 10px",borderRadius:5,border:"none",fontSize:10,fontWeight:600,cursor:"pointer",background:sf===s?"rgba(255,255,255,.05)":"transparent",color:sf===s?"var(--t)":"var(--t3)",fontFamily:"var(--f)"}}>{s==="all"?"All":s==="live"?"Live":"Settled"}</button>)}</div>
<select value={sort} onChange={e=>setSort(e.target.value)} style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:7,padding:"4px 8px",color:"var(--t)",fontSize:10,cursor:"pointer",outline:"none",fontFamily:"var(--f)"}}><option value="newest">Newest</option><option value="highest">Highest</option><option value="lowest">Lowest</option></select>
<div className="dn" style={{position:"relative",width:180}}><div style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",color:"var(--t3)"}}>{I.search(13)}</div><input className="inp" placeholder="Search..." value={sq} onChange={e=>setSq(e.target.value)} style={{paddingLeft:30,height:32,fontSize:11}}/></div>
<button className="bg" onClick={()=>setShowC(true)} style={{padding:"7px 14px",fontSize:11}}>{I.plus(12)} Create</button></div>
<div className="mg" style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:10}}>{filt.map((m,i)=><div key={m.id} className={`mc ${m.st}`} onClick={()=>setShowD(m)} style={{animation:`fu .3s ease backwards`,animationDelay:`${i*.025}s`}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><div style={{display:"flex",alignItems:"center",gap:7}}><Av u={m.cr} size={28}/><div><div style={{fontWeight:600,fontSize:12}}>{m.cr.name}</div><div style={{fontSize:10,color:"var(--t3)"}}>picks <span style={{color:m.cc==="heads"?"var(--g)":"var(--r)",fontWeight:600}}>{m.cc==="heads"?"Heads":"Tails"}</span></div></div></div>{m.st==="live"&&<div style={{display:"flex",alignItems:"center",gap:4,fontSize:10,fontWeight:700,color:"var(--g)"}}><Dot/> LIVE</div>}{m.st==="completed"&&<span className="bd" style={{background:m.res==="heads"?"var(--gd)":"var(--rd)",color:m.res==="heads"?"var(--g)":"var(--r)"}}>{m.res==="heads"?"Heads":"Tails"}</span>}</div>
<div style={{textAlign:"center",marginBottom:10}}><div style={{fontSize:8,color:"var(--t3)",textTransform:"uppercase",letterSpacing:1.2,fontWeight:700,marginBottom:1}}>Stake</div><div style={{fontSize:20,fontWeight:800,fontFamily:MN,color:"var(--g)"}}>${m.ba.toLocaleString()}<span style={{fontSize:10,color:"var(--t3)",fontWeight:500,marginLeft:3}}>{SYM}</span></div></div>
<div style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:3,fontSize:9,fontWeight:600}}><span style={{color:"var(--g)"}}>Heads 50%</span><span style={{color:"var(--r)"}}>Tails 50%</span></div><div style={{display:"flex",height:3,borderRadius:2,overflow:"hidden"}}><div style={{width:"50%",background:"linear-gradient(90deg,#22c55e,#16a34a)"}}/><div style={{width:"50%",background:"linear-gradient(90deg,#dc2626,#ef4444)"}}/></div></div>
{m.st==="live"&&<div style={{display:"flex",gap:6}}><button className="bh" onClick={e=>e.stopPropagation()}>Heads</button><button className="bt" onClick={e=>e.stopPropagation()}>Tails</button></div>}
{m.st==="completed"&&<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:10,color:"var(--t3)",fontFamily:MN}}>${(m.ba*2).toLocaleString()} vol</span><span style={{fontSize:10,color:"var(--t3)"}}>{m.ta}</span></div>}
</div>)}</div>
{filt.length===0&&<div style={{textAlign:"center",padding:50,color:"var(--t3)"}}><div style={{fontSize:13,fontWeight:600}}>No matches found</div></div>}
</div>}

{/* LEADERBOARD */}
{pg==="leaderboard"&&<div style={{animation:"fu .3s ease"}}><div style={{marginBottom:20}}><h1 style={{fontSize:20,fontWeight:800,display:"flex",alignItems:"center",gap:7}}>{I.trophy(18)} Leaderboard</h1><p style={{color:"var(--t2)",fontSize:12,marginTop:3}}>Top players by profit</p></div>
<div className="pg" style={{display:"grid",gridTemplateColumns:"1fr 1.1fr 1fr",gap:10,marginBottom:24,alignItems:"end"}}>{[1,0,2].map(idx=>{const p=lb[idx],isF=idx===0,ls=["1st","2nd","3rd"],bc=["#eab308","#94a3b8","#d97706"];return<div key={idx} style={{background:"var(--card)",border:`1px solid ${isF?"rgba(234,179,8,.2)":"var(--border)"}`,borderRadius:12,padding:isF?24:18,textAlign:"center",animation:`fu .4s ease backwards`,animationDelay:`${idx*.07}s`,order:idx===0?0:idx===1?-1:1}}><div style={{fontSize:9,fontWeight:700,color:bc[idx],textTransform:"uppercase",letterSpacing:1,marginBottom:8}}>{ls[idx]}</div><div style={{display:"flex",justifyContent:"center",marginBottom:8}}><Av u={p} size={isF?44:36}/></div>{isF&&<div style={{marginBottom:1}}>{I.crown(16)}</div>}<div style={{fontWeight:700,fontSize:13}}>{p.name}</div><div style={{color:"var(--g)",fontWeight:800,fontSize:isF?18:15,fontFamily:MN,margin:"3px 0"}}>+${p.pf.toLocaleString()}</div><div style={{color:"var(--t3)",fontSize:10}}>{p.wr}% WR · {p.tw}W</div></div>})}</div>
<div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:11,overflow:"hidden"}}><div className="lr" style={{display:"grid",gridTemplateColumns:"36px 1fr 70px 60px 90px",alignItems:"center",padding:"8px 14px",borderBottom:"1px solid var(--border)",color:"var(--t3)",fontSize:9,fontWeight:700,textTransform:"uppercase",letterSpacing:.8}}><span>#</span><span>Player</span><span className="hm" style={{textAlign:"right"}}>Win Rate</span><span style={{textAlign:"right"}}>Wins</span><span style={{textAlign:"right"}}>Profit</span></div>{lb.slice(3).map((p,i)=><div key={i} className="lr" style={{display:"grid",gridTemplateColumns:"36px 1fr 70px 60px 90px",alignItems:"center",padding:"8px 14px",borderBottom:"1px solid rgba(28,35,51,.4)"}}><span style={{fontWeight:700,color:"var(--t3)",fontFamily:MN,fontSize:11}}>{p.rk}</span><div style={{display:"flex",alignItems:"center",gap:7}}><Av u={p} size={26}/><span style={{fontWeight:600,fontSize:12}}>{p.name}</span></div><span className="hm" style={{textAlign:"right",fontFamily:MN,fontSize:11}}>{p.wr}%</span><span style={{textAlign:"right",fontFamily:MN,fontSize:11}}>{p.tw}</span><span style={{textAlign:"right",fontWeight:700,fontFamily:MN,fontSize:11,color:p.pf>=0?"var(--g)":"var(--r)"}}>{p.pf>=0?"+":""}${p.pf.toLocaleString()}</span></div>)}</div></div>}

{/* MY BETS */}
{pg==="bets"&&<div style={{animation:"fu .3s ease"}}><h1 style={{fontSize:20,fontWeight:800,marginBottom:16,display:"flex",alignItems:"center",gap:7}}>{I.history(18)} My Bets</h1>
<div className="g4" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:20}}>{[{l:"Total Bets",v:"142"},{l:"Win Rate",v:"58.4%"},{l:"Profit",v:"+$2,847",c:"var(--g)"},{l:"Best Streak",v:"7W"}].map((s,i)=><div key={i} style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:11,padding:14}}><div style={{color:"var(--t2)",fontSize:11,marginBottom:5}}>{s.l}</div><div style={{fontSize:18,fontWeight:800,fontFamily:MN,color:s.c||"var(--t)"}}>{s.v}</div></div>)}</div>
<div style={{display:"flex",flexDirection:"column",gap:5}}>{hist.map((h,i)=><div key={h.id} style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:10,padding:"10px 14px",display:"flex",alignItems:"center",gap:10,animation:`fu .3s ease backwards`,animationDelay:`${i*.02}s`}}><div style={{width:32,height:32,borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center",background:h.w?"var(--gd)":"var(--rd)",border:`1px solid ${h.w?"var(--gb)":"var(--rb)"}`,flexShrink:0}}>{h.w?I.check(12):I.xc(12)}</div><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontWeight:600,fontSize:12}}>vs {h.op.name}</span><span className="bd" style={{background:h.res==="heads"?"var(--gd)":"var(--rd)",color:h.res==="heads"?"var(--g)":"var(--r)"}}>{h.res==="heads"?"H":"T"}</span></div><div style={{color:"var(--t3)",fontSize:10,marginTop:1}}>{h.t} · {h.ic?"Creator":"Joiner"} · Fee: ${h.fee.toFixed(2)}</div></div><div style={{textAlign:"right",flexShrink:0}}><div style={{fontWeight:700,fontSize:13,fontFamily:MN,color:h.w?"var(--g)":"var(--r)"}}>{h.net>=0?"+":""}${Math.abs(h.net).toFixed(2)}</div><div style={{fontSize:9,color:"var(--t3)",fontFamily:MN}}>${h.a} {SYM}</div></div></div>)}</div></div>}

{/* REFERRAL */}
{pg==="referral"&&<div style={{animation:"fu .3s ease"}}><h1 style={{fontSize:20,fontWeight:800,marginBottom:4,display:"flex",alignItems:"center",gap:7}}>{I.gift(18)} Referral Program</h1><p style={{color:"var(--t2)",fontSize:12,marginBottom:20}}>Earn 25% of platform fees from every referred user</p>
<div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:12,padding:20,marginBottom:14}}><div style={{fontSize:9,fontWeight:700,color:"var(--t3)",textTransform:"uppercase",letterSpacing:1,marginBottom:6}}>Your Referral Link</div><div style={{display:"flex",gap:6,alignItems:"center"}}><div style={{flex:1,background:"var(--bg)",border:"1px solid var(--border)",borderRadius:8,padding:"8px 12px",fontFamily:MN,fontSize:11,color:"var(--t2)",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>https://randommarkets.xyz/?ref=CW42x9</div><button className="bg" style={{padding:"8px 12px",flexShrink:0,fontSize:11}}>{I.copy(12)} Copy</button></div></div>
<div className="g4" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:20}}>{[{l:"Referrals",v:"23"},{l:"Their Volume",v:"$12,450"},{l:"Earnings",v:"$124.50",c:"var(--g)"},{l:"Pending",v:"$18.20",c:"var(--y)"}].map((s,i)=><div key={i} style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:11,padding:14}}><div style={{color:"var(--t2)",fontSize:11,marginBottom:5}}>{s.l}</div><div style={{fontSize:18,fontWeight:800,fontFamily:MN,color:s.c||"var(--t)"}}>{s.v}</div></div>)}</div>
<div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:12,padding:18}}><div style={{fontSize:13,fontWeight:700,marginBottom:10}}>How it works</div>{["Share your unique referral link","Friends sign up and flip coins","You earn 25% of platform fees","Claim USDC earnings on-chain"].map((s,i)=><div key={i} style={{display:"flex",gap:8,alignItems:"flex-start",marginBottom:8}}><div style={{width:20,height:20,borderRadius:"50%",background:"var(--gd)",border:"1px solid var(--gb)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,color:"var(--g)",flexShrink:0}}>{i+1}</div><span style={{fontSize:12,color:"var(--t2)",lineHeight:1.5}}>{s}</span></div>)}<button className="bg" style={{marginTop:6,width:"100%",justifyContent:"center",padding:11,fontSize:12}}>Claim $18.20 {SYM}</button></div></div>}

{/* FAQ */}
{pg==="faq"&&<div style={{animation:"fu .3s ease",maxWidth:640,margin:"0 auto"}}><h1 style={{fontSize:20,fontWeight:800,marginBottom:16,display:"flex",alignItems:"center",gap:7}}>{I.help(18)} How It Works</h1>{[{q:"What is RandomMarkets?",a:"A provably fair coin flip platform on Base. Create or join matches, pick Heads or Tails, winner takes 2x. Powered by Pyth Entropy."},{q:"What currency?",a:"All bets in USDC on Base network."},{q:"Fees?",a:"Creators: 1.5%. Joiners: 2.5%. Both on top of bet. Winner gets exactly 2x."},{q:"Randomness?",a:"Pyth Entropy commit-reveal protocol. Neither platform nor player can influence outcomes."},{q:"How to connect?",a:"Click Connect — supports MetaMask, Coinbase Wallet, Rainbow, WalletConnect via RainbowKit."},{q:"Cancel a match?",a:"Yes, if unjoined. Bet refunded, creator fee kept."},{q:"Referrals?",a:"Share link. Earn 25% of fees from referrals' matches. Claimable on-chain in USDC."}].map((f,i)=><div key={i} style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:11,padding:"14px 18px",marginBottom:6}}><div style={{fontWeight:700,fontSize:13,marginBottom:4}}>{f.q}</div><div style={{color:"var(--t2)",fontSize:12,lineHeight:1.6}}>{f.a}</div></div>)}</div>}

{/* TERMS */}
{pg==="terms"&&<div style={{animation:"fu .3s ease",maxWidth:640,margin:"0 auto"}}><h1 style={{fontSize:20,fontWeight:800,marginBottom:16}}>Terms & Conditions</h1><div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:12,padding:22}}>{"1. Eligibility — Must be 18+. Restricted jurisdictions prohibited.|2. Risks — Random outcomes. You may lose your entire bet.|3. Fees — Creator: 1.5%. Joiner: 2.5%. Non-refundable after resolution.|4. USDC — Bets in USDC on Base. Not responsible for network fees.|5. Randomness — Pyth Entropy. We cannot influence outcomes.|6. Cancellation — Unjoined matches refundable. Fee retained.|7. Referrals — Abuse may result in restriction.|8. No Warranty — Provided as-is.|9. Modifications — Terms may change. Continued use = acceptance.|10. Liability — Not liable for losses from betting or smart contract issues.".split("|").map((t,i)=><p key={i} style={{color:"var(--t2)",fontSize:12,lineHeight:1.7,marginBottom:10}}>{t}</p>)}<p style={{color:"var(--t3)",fontSize:10,marginTop:14}}>Last updated: February 2026</p></div></div>}

{/* PRIVACY */}
{pg==="privacy"&&<div style={{animation:"fu .3s ease",maxWidth:640,margin:"0 auto"}}><h1 style={{fontSize:20,fontWeight:800,marginBottom:16}}>Privacy Policy</h1><div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:12,padding:22}}>{"Data — Wallet addresses and on-chain data only. No personal info.|Cookies — Minimal analytics. No ad cookies.|On-Chain — All data publicly visible on Base.|Third Parties — No data sold or shared.|Geo — IP data for jurisdiction enforcement only.|Security — Audited contracts. Industry-standard practices.|Rights — Disconnect anytime. On-chain data is immutable.|Contact — Official channels for privacy inquiries.".split("|").map((t,i)=><p key={i} style={{color:"var(--t2)",fontSize:12,lineHeight:1.7,marginBottom:10}}>{t}</p>)}<p style={{color:"var(--t3)",fontSize:10,marginTop:14}}>Last updated: February 2026</p></div></div>}

{/* ABOUT */}
{pg==="about"&&<div style={{animation:"fu .3s ease",maxWidth:640,margin:"0 auto"}}><h1 style={{fontSize:20,fontWeight:800,marginBottom:16}}>About RandomMarkets</h1><div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:12,padding:22,marginBottom:14}}><p style={{color:"var(--t2)",fontSize:13,lineHeight:1.7,marginBottom:14}}>Provably fair coin flip platform on Base. Transparent, verifiable, trustless betting.</p><p style={{color:"var(--t2)",fontSize:13,lineHeight:1.7,marginBottom:14}}>Every flip powered by Pyth Entropy — cryptographic commit-reveal ensuring no one can influence outcomes. Bets settle in USDC.</p><p style={{color:"var(--t2)",fontSize:13,lineHeight:1.7}}>Low fees. Fast confirmations. Open-source contracts. No house edge beyond platform fees.</p></div><div className="g4" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>{[{l:"Chain",v:"Base"},{l:"Currency",v:"USDC"},{l:"Randomness",v:"Pyth Entropy"}].map((s,i)=><div key={i} style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:11,padding:14,textAlign:"center"}}><div style={{color:"var(--t3)",fontSize:9,marginBottom:3,fontWeight:700,textTransform:"uppercase",letterSpacing:.5}}>{s.l}</div><div style={{fontSize:14,fontWeight:800}}>{s.v}</div></div>)}</div></div>}

{/* GEO DISCLAIMER */}
{mP.includes(pg)&&<div style={{marginTop:28,padding:"10px 14px",background:"rgba(239,68,68,.03)",border:"1px solid rgba(239,68,68,.08)",borderRadius:9,display:"flex",alignItems:"flex-start",gap:7}}>{I.info(12)}<p style={{fontSize:10,color:"var(--t2)",lineHeight:1.5}}><strong style={{color:"var(--r)"}}>Restricted Jurisdictions:</strong> Not available in certain countries. By using RandomMarkets you confirm legal eligibility. See <span onClick={()=>nav("terms")} style={{color:"var(--u)",cursor:"pointer",textDecoration:"underline"}}>Terms</span>.</p></div>}
</main>

{/* FOOTER */}
<footer style={{borderTop:"1px solid var(--border)",padding:16,maxWidth:1200,margin:"32px auto 0"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10}}><div style={{display:"flex",alignItems:"center",gap:5,fontSize:12,fontWeight:700}}>{I.coin(14)} Random<span style={{color:"var(--g)"}}>Markets</span></div><div style={{display:"flex",gap:14}}>{[{l:"Terms",p:"terms"},{l:"Privacy",p:"privacy"},{l:"FAQ",p:"faq"},{l:"About",p:"about"}].map(x=><span key={x.p} onClick={()=>nav(x.p)} style={{color:"var(--t3)",fontSize:11,cursor:"pointer"}}>{x.l}</span>)}</div><div style={{color:"var(--t3)",fontSize:10}}>Base · Pyth Entropy · USDC</div></div></footer>

{showC&&<CreateMod close={()=>setShowC(false)} bal={bal}/>}
{showD&&<DetailMod m={showD} close={()=>setShowD(null)} bal={bal}/>}
</div>}
